#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-accesibilidad
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) 2011 Carlos Andrés Escobar <carlosescobar70@gmail.com>
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
#
# ==============================================================================
#
# Agradeciminetos: 
#	Proyecto un Mundo Accesible <l-accesible@listas.mundoaccesible.org.ve>
#	Nerisa Aguilera <naguilera1008@gmail.com>
#	Joel Gomez <joelgomezb@gmail.com>
#	Flavio Percoco <flaper87@gmail.com>
#
#	por su aporte mediante el  script  tiflo_system.sh, el cual sirvio para complementar el postinst de canaima-accesibilidad
#
# ============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-accesibilidad"

case ${1} in

	remove|upgrade|deconfigure)
	;;

	failed-upgrade)
	;;

	*)

		echo "prerm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
